data = [
  {id: 1, name: "Grandma's Sample", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Breakfast/Traditional-Favorites/Grandmas-Sampler_780x390.jpg", description: "Two Buttermilk Pancakes served with your own warm bottle of 100% Pure Natural Syrup, two eggs,* one strip of Thick-Sliced Bacon, one Smoked Sausage Patty, and a sampling of Sugar Cured or Country Ham. Served with Hashbrown Casserole or Fried Apples."},
  {id: 2, name: "Buttermilk Pancakes with Fruit Toppings", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Breakfast/Pancakes-n-Such/Pancakes_with_Fruit_Topping_780x390.jpg", description: "Three of our Buttermilk Pancakes with your choice of any fruit Sweet Topping."},
  {id: 3, name: "Eggs-in-the-Basket", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Breakfast/Everyday-Favorites/Eggs_in_the_Basket_780x390.jpg", description: "Two slices of our Sourdough bread, each grilled with an egg* in the middle and your choice of Hashbrown Casserole or Fried Apples plus Thick-Sliced Bacon or sausage."},
  {id: 4, name: "Fresh Fruit n' Yogurt Parfait Breakfast", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Breakfast/Wholesome-Fixins/Fresh_Fruit_n_Yogurt_Parfait_Bfast_Fall-Spring_780x390.jpg", description: "Low-fat vanilla yogurt and Fresh Seasonal Fruit topped with honey oats, almonds and dried fruit granola. Served with two Scrambled Egg Whites and Turkey Sausage."},
  {id: 5, name: "Apple n' Cinnamon Oatmeal", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Breakfast/Wholesome-Fixins/Apple_n_Cinnamon_Oatmeal_WF-780x390.jpg", description: "Hearty steel-cut oats simmered ‘til creamy with dried cranberries, apples, golden raisins, cinnamon and vanilla, and topped with roasted Fuji apples, dried cranberries and pecans. Served with reduced fat milk."},
  {id: 6, name: "Fresh Start Sampler", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Breakfast/Traditional-Favorites/Fresh-Start-Breakfast_Spring-Fall_780x390.jpg", description: "Enjoy a mix of low-fat vanilla yogurt and Fresh Seasonal Fruit topped with honey oat, almond and dried fruit granola. Served with two farm fresh eggs* plus our house-baked Wild Maine Blueberry Muffin and Turkey Sausage, Thick-Sliced Bacon or Smoked Sausage Patties."},
  {id: 7, name: "Biscuits n' Gravy with Bacon or Sausage", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Breakfast/Everyday-Favorites/Biscuits_Gravy-_Bacon_780x390.jpg", description: "Three Buttermilk Biscuits with Sawmill Gravy and Thick-Sliced Bacon or sausage patties."},
  {id: 8, name: "Good Morning Breakfast", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Breakfast/Wholesome-Fixins/GMB_Fall_Spring_WF_780x390.jpg", description: "Two Scrambled Egg Whites, Coarse Ground Grits, a side of Fresh Seasonal Fruit, sliced tomatoes and Turkey Sausage."},
  {id: 9, name: "Meat Biscuits n' Hashbrown Casserole or Fried Apples", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Breakfast/Everyday-Favorites/Meat_Biscuit_Hashbrown_Casserole-H_780x390.jpg", description: "Two hand-rolled Buttermilk Biscuits with choice of Ham, Sausage Patty, or Thick-Sliced Bacon, served with Fried Apples or Hashbrown Casserole."},
  {id: 10, name: "Egg Sandwich", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Breakfast/Everyday-Favorites/Egg-Sandwich_780x390.jpg", description: "Two farm fresh eggs* served on seared Sourdough bread with tomato and mayo and your choice of Fried Apples or Hashbrown Casserole."},
  {id: 11, name: "Uncle Herschel's Favorite", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Breakfast/Traditional-Favorites/Uncle-Herschels-Favorite_780x390.jpg", description: "Two farm fresh eggs* with grits and your choice of Fried Apples or Hashbrown Casserole and your choice of meat: Sugar Cured Ham, U.S. Catfish Fillet grilled or fried, 8 oz. Hamburger Steak,** Hickory-Smoked Country Ham, Fried Chicken Tenderloins, or Grilled Pork Chop. Comes with All the Fixin’s: Sawmill Gravy, homemade Buttermilk Biscuits, real butter and the best Preserves n’ Jam."},
  {id: 12, name: "The Cracker Barrel's Country Boy Breakfast", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Breakfast/Traditional-Favorites/Country-Boy-Breakfast_780x390.jpgx", description: "Enjoy three eggs*, Fried Apples, Hashbrown Casserole and grits plus Two Pork Chops or Country Ham or Sirloin Steak*. Comes with All the Fixin’s: Sawmill Gravy, homemade Buttermilk Biscuits, real butter and the best Preserves n’ Jam."},
];
module.exports = data;
