data2 = [
  {id: 201, price:"15", name: "Country Fried Steak", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Dinner/Fancy-Fixins/Country_Fried_Steak_FF-H_780x390.jpg", description: "A generous serving of USDA Choice steak breaded and deep fried and topped with our classic Sawmill Gravy. Served with your choice of three country sides and homemade Buttermilk Biscuits or Corn Muffins."},
  {id: 202, price:"15", name: "Roast Beef", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Dinner/Fancy-Fixins/Roastbeef_FF-H_780x390.jpg", description: "A savory favorite, featuring USDA Choice Chuck Roast slow-cooked for 14 hours. Served with choice of three country sides and homemade Buttermilk Biscuits or Corn Muffins."},
  {id: 203, price:"10", name: "Meatloaf", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Dinner/Fancy-Fixins/Meatloaf_FF-H_780x390.jpg", description: "A thick slice of our special recipe Meatloaf made with tomatoes, onions and green peppers. Comes with three country sides and made-from-scratch Buttermilk Biscuits or Corn Muffins."},
  {id: 204, price:"20", name: "10 oz. Rib Eye Steak", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Dinner/Fancy-Fixins/Ribeye_Steak_FF-H_780x390.jpg", description: "Our thick-cut USDA Choice rib eye* is aged 28 days for exceptional tenderness and flavor, lightly seasoned and grilled to order. Comes with three country sides and made-from-scratch Buttermilk Biscuits or Corn Muffins. Enjoy it with a House Salad and Baked Potato in place of your three sides."},
  {id: 205, price:"15", name: "Grilled Sirloin Steak", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Dinner/Fancy-Fixins/Grilled-Sirloin_Steak_FF-H_780x390.jpg", description: "Our 8 oz. USDA Choice top sirloin, seasoned and grilled to order. Comes with three country sides and made-from-scratch Buttermilk Biscuits or Corn Muffins. Enjoy it with a House Salad and Baked Potato in place of your three sides."},
  {id: 206, price:"15", name: "Cracker Barrel Sampler", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Dinner/Fancy-Fixins/CB_Sampler_FF-H_780x390.jpg", description: "A hearty sampling of our Chicken n’ Dumplins, Meatloaf and sugar cured or country ham. Comes with three country sides and made-from-scratch Buttermilk Biscuits or Corn Muffins."},
  {id: 207, price:"15", name: "Half-Pound Hamburger Steak", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Dinner/Country-Dinner-Plates/Hamburger_Steak_CDP_780x390.jpg", description: "Our Country Dinner Plates are served with your choice of two country vegetables plus homemade Buttermilk Biscuits or Corn Muffins."},
  {id: 208, price:"15", name: "Prime Rib French Dip Sandwich Platter", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Dinner/Country-Sandwich-Platters/French-Dip_780x390.jpg", description: "We hope you enjoy Prime Rib that’s roasted slow and served with fresh grilled onions, beef au jus, Swiss Cheese, and Peppercorn Horseradish Sauce on a toasted hoagie bun. It comes with Homestyle Fries or a Cup of Soup, and a sampling of Cole Slaw."},
  {id: 209, price:"12", name: "Chicken BLT", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Dinner/Country-Sandwich-Platters/Chicken_BLT-H_780x390.jpg", description: "Your choice of our grilled or fried chicken tenderloins topped with Thick-Sliced Bacon, Colby cheese, mayo, lettuce and tomato on seared Sourdough bread."},
  {id: 210, price:"5", name: "Signature Burger", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Dinner/Country-Sandwich-Platters/Signature_Burger-H_780x390.jpg", description: "Two patties* topped with Colby cheese, mayo, and finished with lettuce and tomatoes. Available with one patty."},
  {id: 211, price:"10", name: "Maple Jam n' Bacon Burger", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Dinner/Country-Sandwich-Platters/Maple_Bacon_Burger-H_780x390.jpg", description: "Two patties* topped with maple pepper bacon, Colby cheese, maple onion jam, and finished with lettuce and tomatoes. Available with one patty."},
  {id: 212, price:"5", name: "Grilled Chicken Salad", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Seasonal/FY18-Fall-Promo/Grilled-Chicken-Salad_Fall-FY18-H_780x390.jpg", description: "Tender grilled chicken served up over fresh romaine and spring mix with grape tomatoes, shredded Colby cheese, English cucumbers, two deviled eggs, a wedge of Colby cheese, and house-baked sourdough croutons. Comes with your choice of dressing and Westminster Crackers®."},
];
module.exports = data2;
