data1 = [
  {id: 101, price:"20", name: "Turkey n' Dressing", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Dinner/Daily-Dinner-Features/Turkey_n_Dressing_DDF-H_780x390.jpg", description: "Our very own roasted Turkey n’ Dressing with choice of two Country Vegetables plus made-from-scratch Buttermilk Biscuits or Corn Muffins. Served starting at 4pm."},
  {id: 102, price:"25", name: "Lemon Pepper Rainbow Trout", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Dinner/Daily-Dinner-Features/Lemon_Pepper_Grilled_Rainbow_Trout_DDF-H_780x390.jpg", description: "Two lightly seasoned boneless spring water trout fillets grilled until fork tender. Comes with two country sides and made-from-scratch Buttermilk Biscuits or Corn Muffins. Served starting at 4pm."},
  {id: 103, price:"20", name: "Fish Fry", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Dinner/Daily-Dinner-Features/Fish_Fry_Cod_DDF-H_780x390.jpg", description: "Starting at 11 AM, we serve four Cod fillets, hand-dipped in our own special batter and fried. We suggest enjoying them with Homestyle Fries and Cole Slaw. "},
  {id: 104, price:"20", name: "Chicken n' Rice", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Dinner/Daily-Dinner-Features/Chicken_n_Rice_DDF-H_780x390.jpg", description: "Starting at 11 AM, we serve our made-from-scratch Chicken n’ Rice. Our chicken tenderloins are simmered in a hearty chicken mushroom gravy and served on top of our new seasoned rice."},
  {id: 105, price:"19", name: "Sunday Homestyle Chicken", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Dinner/Daily-Dinner-Features/Homestyle_Chicken_DDF-H_780x390.jpg", description: "Starting at 11 AM, enjoy two boneless chicken breasts, hand-dipped in our special buttermilk batter, breaded and deep fried to a crispy golden brown in our kitchen."},
  {id: 106, price:"20", name: "Broccoli Cheddar Chicken", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Dinner/Daily-Dinner-Features/Broccoli_Cheddar_Chicken_DDF-H_780x390.jpg", description: "Oven baked Broccoli Cheddar Chicken with choice of two Country Vegetables plus made-from-scratch Buttermilk Biscuits or Corn Muffins. Served starting at 4pm."},
  {id: 107, price:"20", name: "Grilled Pork Chops", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Dinner/Daily-Dinner-Features/Grilled_PorkChop_DDF-H_780x390.jpg", description: "Two bone-in Grilled Country Pork Chops with choice of two Country Vegetables plus made-from-scratch Buttermilk Biscuits or Corn Muffins. Served starting at 4pm."},
  {id: 108, price:"15", name: "Hot Soups", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Dinner/Specials/Cup_Veg_Soup_CB_Specialties_780x390.jpg", description: "Served with Westminster Crackers®. Be sure to ask which selections are available today."},
  {id: 109, price:"20", name: "Beans n' Greens", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Dinner/Specials/Beans_n_Greens_CB_Specialties_780x390.jpg", description: "A cup of our Pinto Beans and Turnip Greens cooked with our country ham and served with an onion slice, chow chow relish and vinegar. Served with Corn Muffins plus real butter."},
  {id: 110, price:"10", name: "Bowl of Pinto Beans", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Dinner/Vegetables-n-Sides/Pinto_Beans_Veg_N_Sides_780x390.jpg", description: "Cooked with our country ham and served with an onion slice and chow chow relish. Comes with Corn Muffins plus real butter."},
  {id: 111, price:"20", name: "Southern Grilled Chicken Caesar", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Dinner/Salads/Southern_Grilled_Caesar_Salad-H_780x390.jpg", description: "Smoky Southern grilled chicken breast over chopped Romaine lettuce tossed in Buttermilk Caesar dressing. Topped with shaved Parmesan, grape tomatoes, house-baked Sourdough croutons and two deviled eggs."},
  {id: 112, price:"20", name: "Lemon Pepper Grilled Rainbow Trout Plate", thumbnail: "https://crackerbarrel.com/-/media/CrackerBarrel/Menu/Dinner/Country-Dinner-Plates/Lemon_Pepper_Grilled_Rainbow_Trout_CDP_780x390.jpg", description: "Lightly seasoned boneless spring water trout fillet grilled until fork tender. Comes with your choice of Country Sides and made-from-scratch Buttermilk Biscuits or Corn Muffins."},
];
module.exports = data1;
